### ISSUE TITLE
License is not clear

### ISSUE THREAD

**Issue by erikvanoosten** [NewMotion/docile-charge-point#12]
Please see here for ideas: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

**Comment by reinierl** [comment]
Oh sorry. It's supposed to be GPL. If we made it state something more permissive like MIT or BSD, it would effectively still be GPL v3 because it's solidly based on the NewMotion OCPP library which is licensed under the GPL v3. I'll add an explicit license. Thanks for the heads-up.

**Comment by reinierl** [comment]
By the way, 14-year-old Linux hobbyist me can't believe 34-year-old professional developer me is now reading advice on open source licensing from Microsoft, eh sorry, I mean "M$" :P
