### ISSUE TITLE
Unable to build : 403 Error

### ISSUE THREAD

**Issue by RevenMyst** [NewMotion/docile-charge-point#22]
Hello !
I'm trying to build the simulator in order to use it, however, sbt is unable to get some dependencies because of a 403 Error on the following URL :  https://nexus.thenewmotion.com
Thx !

**Comment by shadsnz** [comment]
I'm also having problems running sbt assembly.  The exact error I see reported is:

sbt.librarymanagement.ResolveException: Error downloading com.thenewmotion.ocpp:ocpp-j-api_2.12:9.2.3

**Comment by reinierl** [comment]
It seems that NewMotion have changed the hosting of the artifacts of their open source projects. See e.g. https://github.com/NewMotion/ocpp/commit/f5fc5d82c0c2cea0f9501a4fca6dd80fc268fdf5. @markvandertol do you know if changing the dependency declaration to what's documented there will fix this?

**Comment by markvandertol** [comment]
Hi!

We removed our public repository. Unfortunately, this means building this project requires a bit more effort from your part. We'll look at the options to streamline this for the future, either by improving the guide or publishing the library somewhere else. I cannot give a timeline at this point.

For now: You have to download and compile [ocpp-j-api library](https://github.com/NewMotion/ocpp) locally. Then you can build this project.

**Comment by reinierl** [comment]
@markvandertol How interested are you guys anyway to maintain these projects as open source projects within NewMotion? Otherwise it might be easier for me to import a fork of the OCPP library into docile and continue its main development at the IHomer repo.

**Comment by markvandertol** [comment]
@reinierl We don't expect a lot of new development on these public libraries, so your suggestion sounds like a good idea!

**Comment by reinierl** [comment]
@RevenMyst It's finally done. We've set up forks of NewMotion's OCPP and docile-charge-point at https://github.com/IHomer/scala-ocpp and https://github.com/IHomer/docile-charge-point. Those build and they're published to Maven Central so everyone can use them.

**Comment by olger** [comment]
The end of a joyous era - good luck with the continued development at IHomer @reinierl
